name: packer

on:
  - pull_request

jobs:
  packer:
    runs-on: windows-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3" 

      - name: Run `packer init`
        id: init
        run: "packer init aws.ubuntu.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate aws.ubuntu.pkr.hcl"